/* Component/flow tests in a simulated DOM. These are not rendered browser tests. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let JSDOM,IDBFactory;
try{({JSDOM}=require('jsdom'));({IDBFactory}=require('fake-indexeddb'));}catch{({JSDOM}=require('../../../test-runtime/node_modules/jsdom'));({IDBFactory}=require('../../../test-runtime/node_modules/fake-indexeddb'));}
const clone=x=>JSON.parse(JSON.stringify(x));
const fixture={brand:'Lilien',type:'Liquid Soap',id:'8596048008129',hs:'00123456',name:'TEST Soap',csName:'TEST Mýdlo',volume:{number:'500',unit:'ml',note:'keep'},price:1.2,key:'500A',pack:12,boxes_per_layer:20,boxes_per_pallet:160,carton_ean:'00123456789012',new:false,new_date:'',discontinued:false,discontinued_date:'',custom:{keep:['yes']}};
const logistics={Lilien:{'500A':{ITEM:{length:'5 cm',width:'5 cm',height:'15 cm',weight:'0.5 kg'},CARTON:{length:'30 cm',width:'20 cm',height:'20 cm',weight:'6 kg',nr_of_items:12},LAYER:{nr_of_items:240,nr_of_cartons:20},PALLET:{length:'120 cm',width:'80 cm',height:'150 cm',weight:'500 kg',nr_of_cartons:160,nr_of_items:1920,nr_of_layers:8},extra:{keep:'supplier'}}}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn){for(let i=0;i<150;i++){if(await fn())return;await sleep(10);}throw Error('Wait condition timed out');}
async function setup(shared=false,initialRemote=null){
 const errors=[],html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
 const dom=new JSDOM(html,{url:shared?'https://feela-cz.github.io/Union-Cosmetic/Jason2/':'https://local.test/Jason2/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 w.indexedDB=new IDBFactory();w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.HTMLAnchorElement.prototype.click=function(){};w.URL.createObjectURL=()=>'blob:test';w.URL.revokeObjectURL=()=>{};
 w.fetch=async()=>({ok:false,status:404,text:async()=>'',json:async()=>{throw Error('404');}});
 w.console.error=e=>errors.push(e.message||String(e));
 w.eval(fs.readFileSync(path.join(__dirname,'../config.js'),'utf8'));if(!shared){w.JASON_CONFIG.sharedOnly=false;w.JASON_CONFIG.autoConnect=false;w.JASON_SEED_LOGISTICS=JSON.parse(fs.readFileSync(path.join(__dirname,'../../JSON edit GUI/logistics.json'),'utf8'));}if(initialRemote)w.fetch=initialRemote;
 w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;
 for(const name of ['model.js','storage.js','i18n.js','vendor/exceljs.min.js','export.js','app.js'])w.eval(fs.readFileSync(path.join(__dirname,'..',name),'utf8'));
 const $=s=>w.document.querySelector(s),$$=s=>[...w.document.querySelectorAll(s)],click=s=>{const e=$(s);assert.ok(e,`Missing ${s}`);assert.ok(!e.disabled,`Disabled ${s}`);e.click();},input=(s,v)=>{const e=$(s);assert.ok(e,`Missing ${s}`);e.value=v;e.dispatchEvent(new w.Event('input',{bubbles:true}));},change=(s,v)=>{const e=$(s);e.value=v;e.dispatchEvent(new w.Event('change',{bubbles:true}));};
 await wait(()=>$('#page-title').textContent==='Produkty');
 const saved=async()=>clone((await w.JasonStorage.get('state'))?.state);
 async function upload(kind,data,confirm=true){click('#data-button');click(kind==='products'?'#import-products':kind==='logistics'?'#import-logistics':'#restore-backup');Object.defineProperty($('#import-file'),'files',{configurable:true,value:[{name:'test.json',size:JSON.stringify(data).length,text:async()=>JSON.stringify(data)}]});$('#import-file').dispatchEvent(new w.Event('change'));if(confirm){await wait(()=>$('#confirm-dialog').open);click('#confirm-yes');await wait(()=>!$('#editor').open);}}
 const submit=s=>{$(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));};
 return {w,dom,$,$$,click,input,change,saved,upload,submit,errors};
}
(async()=>{
 let passed=0;const c=await setup(),{w,$,$$,click,input,change,saved,upload,submit,errors}=c;
 async function test(name,fn){await fn();passed++;console.log('PASS',name);}
 await test('product logistics detail shows full key, exports it and preserves unsaved product draft',async()=>{
  const n=await setup(),keys=clone(logistics);keys.Lilien['500A'].ITEM.weight='0 kg';keys.Natava={'500A':clone(keys.Lilien['500A'])};keys.Natava['500A'].CARTON.nr_of_items=24;
  await n.upload('products',[fixture]);await n.upload('logistics',keys);const before=await n.saved();
  n.click('[data-edit="0"]');n.input('#field-name','UNSAVED PRODUCT');n.click('#tab-packaging');
  assert.equal(n.$$('#product-key-data section').length,4);assert.equal(n.$$('#product-key-data dd').length,18);assert.ok(n.$$('#product-key-data dd').some(el=>el.textContent==='0'));
  let wb;n.w.JasonExport.download=async book=>{wb=book;};n.click('#product-key-export');await wait(()=>wb);assert.deepEqual(Array.from(wb.worksheets,s=>s.name),['Lilien']);assert.equal(wb.getWorksheet('Lilien').columnCount,3);assert.equal(wb.getWorksheet('Lilien').getCell('C2').value,'500A');assert.equal(wb.getWorksheet('Lilien').getCell('C6').value,0);await wait(()=>!n.$('#product-key-export').disabled);
  n.click('#product-key-open');assert.ok(n.$('#key-preview-dialog').open);assert.equal(n.$('#key-preview-title').textContent,'Lilien / 500A');assert.equal(n.$$('#key-preview-body dd').length,18);
  n.w.document.dispatchEvent(new n.w.KeyboardEvent('keydown',{key:'s',ctrlKey:true,bubbles:true,cancelable:true}));await sleep(20);assert.ok(n.$('#editor').open);assert.equal((await n.saved()).products[0].name,fixture.name);
  wb=null;n.click('#key-preview-export');await wait(()=>wb);await wait(()=>!n.$('#key-preview-export').disabled);assert.equal(wb.getWorksheet('Lilien').getCell('C11').value,12);assert.equal(wb.getWorksheet('Lilien').getCell('A1').fill.fgColor.argb,'FF214A84');
  n.click('#key-preview-close');assert.ok(n.$('#editor').open);assert.equal(n.$('#field-name').value,'UNSAVED PRODUCT');
  n.change('#product-key','');assert.ok(n.$('#product-key-open').disabled);assert.ok(n.$('#product-key-export').disabled);assert.equal(n.$$('#product-key-data dd').length,0);
  n.input('#field-brand','Natava');n.change('#field-brand','Natava');n.change('#product-key','500A');assert.equal(n.$('#field-pack').value,'24');
  wb=null;n.click('#product-key-export');await wait(()=>wb);assert.deepEqual(Array.from(wb.worksheets,s=>s.name),['Natava']);assert.equal(wb.getWorksheet('Natava').getCell('C11').value,24);
  assert.deepEqual(await n.saved(),before);assert.deepEqual(n.errors,[]);n.dom.window.close();
 });
 await test('new flag keeps its status badge and filters independently, including exports',async()=>{
  const n=await setup();
  const products=[{...fixture,id:'active',new:false},{...fixture,id:'active-new',new:true},{...fixture,id:'old-new',new:true,discontinued:true}];
  await n.upload('products',products);
  assert.deepEqual(n.$$('#filter-status option').map(o=>o.value),['active','all','discontinued']);
  assert.equal(n.$$('tbody tr').length,2);
  assert.equal(n.$$('tbody .status-active').length,2);assert.equal(n.$$('tbody .status-new').length,1);
  n.change('#filter-new','yes');assert.equal(n.$$('tbody tr').length,1);assert.ok(n.$('tbody .status-active'));assert.ok(n.$('tbody .status-new'));
  let wb;n.w.JasonExport.download=async book=>{wb=book;};n.click('#export');n.submit('#export-form');await wait(()=>wb);assert.equal(wb.getWorksheet('Products').getCell('C4').value,'active-new');assert.equal(wb.getWorksheet('Products').rowCount,4);await wait(()=>!n.$('#export-form [type=submit]').disabled);n.click('#editor-close');
  n.change('#filter-status','discontinued');assert.equal(n.$$('tbody tr').length,1);assert.ok(n.$('tbody .status-discontinued'));assert.ok(n.$('tbody .status-new'));
  n.change('#filter-new','no');assert.equal(n.$$('tbody tr').length,0);
  n.change('#filter-status','active');assert.equal(n.$$('tbody tr').length,1);assert.equal(n.$('tbody .status-new'),null);
  n.click('#reset');assert.equal(n.$('#filter-status').value,'active');assert.equal(n.$('#filter-new').value,'');assert.equal(n.$$('tbody tr').length,2);
  assert.deepEqual((await n.saved()).products,products);n.dom.window.close();
 });
 await test('empty catalog and archived logistics initialized',async()=>{assert.ok($('#empty-import'));assert.ok(Number($('[data-view=keys] .nav-count').textContent)>0);});
 await test('import authentic JSON structure and search without accents',async()=>{await upload('products',[fixture]);await upload('logistics',logistics);input('#search','mydlo 859');assert.equal($$('tbody tr').length,1);click('#reset');assert.equal((await saved()).products[0].hs,'00123456');});
 await test('product edit retains unknown fields and exact identifiers',async()=>{click('[data-edit="0"]');input('#field-price','2.45');click('#tab-flags');input('#field-flags','Promo, Export');submit('#product-form');await wait(()=>!$('#editor').open);const p=(await saved()).products[0];assert.equal(p.price,2.45);assert.deepEqual(p.custom,fixture.custom);assert.equal(p.volume.note,'keep');assert.equal(p.carton_ean,fixture.carton_ean);assert.deepEqual(p.flags,['Promo','Export']);});
 await test('duplicate EAN blocks save; copying preserves unknown fields',async()=>{click('[data-more="0"]');click('#action-copy');input('#field-id',fixture.id);submit('#product-form');await wait(()=>!$('#form-error').hidden);assert.match($('#form-error').textContent,/už používá/);assert.equal((await saved()).products.length,1);input('#field-id','0000000000000');input('#field-name','TEST Copy');submit('#product-form');await wait(()=>!$('#editor').open);assert.equal((await saved()).products.length,2);assert.deepEqual((await saved()).products[1].custom,fixture.custom);});
 await test('undo and redo preserve data',async()=>{click('#undo');await wait(async()=>(await saved()).products.length===1);click('#redo');await wait(async()=>(await saved()).products.length===2);});
 await test('shared key editing, renaming and all-product packaging sync',async()=>{click('[data-view=keys]');click('[data-key-edit="Lilien"]');input('[name="CARTON:nr_of_items"]','6');input('#field-key','500B');submit('#key-form');await wait(()=>$('#confirm-dialog').open);click('#confirm-yes');await wait(()=>!$('#editor').open);const s=await saved();assert.ok(s.products.every(p=>p.pack===6&&p.key==='500B'));assert.equal(s.logistics.Lilien['500A'],undefined);assert.equal(s.logistics.Lilien['500B'].extra.keep,'supplier');assert.equal(s.products[0].carton_ean,fixture.carton_ean);});
 await test('copy key retains values and supplier extension',async()=>{click('[data-key-edit="Lilien"]');click('#key-copy');assert.equal($('[name="CARTON:nr_of_items"]').value,'6');input('#field-key','500C');submit('#key-form');await wait(()=>!$('#editor').open);const s=await saved();assert.equal(s.logistics.Lilien['500C'].CARTON.nr_of_items,6);assert.equal(s.logistics.Lilien['500C'].extra.keep,'supplier');});
 await test('used key deletion prevented; unused deletion recoverable',async()=>{click('[data-key-name="500B"][data-key-edit]');assert.equal($('#key-delete').disabled,true);click('#editor-close');click('[data-key-name="500C"][data-key-edit]');click('#key-delete');click('#confirm-yes');await wait(()=>!$('#editor').open);assert.equal((await saved()).logistics.Lilien['500C'],undefined);});
 await test('new product derives packaging from selected key',async()=>{click('[data-view=products]');click('#create');input('#field-brand','Lilien');change('#field-brand','Lilien');input('#field-id','0000000000001');input('#field-name','TEST New');input('#field-csName','TEST Nový');input('#field-price','0');click('#tab-packaging');change('#product-key','500B');assert.equal($('#field-pack').value,'6');submit('#product-form');await wait(()=>!$('#editor').open);const p=(await saved()).products[2];assert.equal(p.pack,6);assert.equal(p.price,0);});
 await test('bulk discontinuation and all/discontinued filters',async()=>{click('#select-page');click('#bulk-edit');change('[name=operation]','setDisc');submit('#bulk-form');await wait(()=>!$('#editor').open);assert.equal($$('tbody tr').length,0);change('#filter-status','discontinued');assert.equal($$('tbody tr').length,3);assert.ok((await saved()).products.every(p=>p.discontinued&&p.discontinued_date));});
 await test('product XLSX content uses text identifiers and current filters',async()=>{let workbook;w.JasonExport.download=async wb=>{workbook=wb;};click('#export');submit('#export-form');await wait(()=>workbook);const ws=workbook.getWorksheet('Products');assert.equal(typeof ws.getCell('C4').value,'string');assert.equal(ws.rowCount,6);assert.ok(ws.getColumn(3).values.includes('0000000000000'));assert.equal(ws.getCell('H4').numFmt,'0.00 "€"');assert.equal(ws.getCell('A1').fill.fgColor.argb,'FF214A84');await wait(()=>!$('#export-form [type=submit]').disabled);click('#editor-close');});
 await test('checked products override filtered export and the dialog shows the selected count',async()=>{
  let wb;w.JasonExport.download=async x=>{wb=x;};click('[data-select="0"]');click('#export');assert.match($('#export-options').textContent,/1 produktů.*vybrané položky/);submit('#export-form');await wait(()=>wb);assert.equal(wb.getWorksheet('Products').rowCount,4);assert.equal(wb.getWorksheet('Products').getCell('C4').value,fixture.id);await wait(()=>!$('#export-form [type=submit]').disabled);click('#editor-close');click('#bulk-clear');
 });
 await test('product selection exports across pages and clearing it restores filtered export',async()=>{
  const pages=await setup(),rows=Array.from({length:35},(_,i)=>({...fixture,id:String(1000000000000+i),name:'TEST PAGE '+String(i).padStart(3,'0'),csName:'TEST PAGE '+String(i).padStart(3,'0')}));
  await pages.upload('products',rows);let wb;pages.w.JasonExport.download=async x=>{wb=x;};pages.click('[data-select="0"]');pages.click('#next');pages.click('[data-select="30"]');pages.click('#export');assert.match(pages.$('#export-options').textContent,/2 produktů.*vybrané položky/);pages.submit('#export-form');await wait(()=>wb);const ws=wb.getWorksheet('Products');assert.equal(ws.rowCount,5);assert.deepEqual([ws.getCell('C4').value,ws.getCell('C5').value].sort(),[rows[0].id,rows[30].id].sort());await wait(()=>!pages.$('#export-form [type=submit]').disabled);pages.click('#editor-close');pages.click('#bulk-clear');pages.input('#search',rows[0].id);wb=null;pages.click('#export');assert.match(pages.$('#export-options').textContent,/1 produktů.*aktuálních filtrů/);pages.submit('#export-form');await wait(()=>wb);assert.equal(wb.getWorksheet('Products').rowCount,4);pages.dom.window.close();
 });
 await test('logistics XLSX matrix exports partial keys, numeric counts and units',async()=>{let wb;w.JasonExport.download=async x=>{wb=x;};click('[data-view=keys]');click('#export');submit('#export-form');await wait(()=>wb);const ws=wb.getWorksheet('Lilien');assert.equal(ws.getCell('C2').value,'500B');assert.equal(ws.getCell('C11').value,6);assert.match(ws.getCell('B3').value,/\(cm\)/);assert.match(ws.getCell('B6').value,/\(kg\)/);assert.notEqual(ws.getCell('A3').fill.fgColor.argb,ws.getCell('A7').fill.fgColor.argb);await wait(()=>!$('#export-form [type=submit]').disabled);click('#editor-close');});
 await test('data checks detect arithmetic inconsistency and open affected key',async()=>{click('[data-view=checks]');assert.ok($('#content').textContent.includes('nesouhlasí'));click('[data-issue]');assert.ok($('#editor').open);click('#editor-close');});
 await test('invalid JSON import leaves state unchanged',async()=>{const before=await saved();await upload('products',{bad:true},false);await wait(()=>$('#toast').textContent.includes('formát'));assert.deepEqual((await saved()).products,before.products);click('#editor-close');errors.length=0;});
 await test('unsaved form close prompts and cancellation retains work',async()=>{click('[data-view=products]');change('#filter-status','all');click('[data-edit="0"]');input('#field-name','UNSAVED');click('#editor-close');await wait(()=>$('#confirm-dialog').open);click('#confirm-no');assert.ok($('#editor').open);click('#editor-close');click('#confirm-yes');await wait(()=>!$('#editor').open);assert.equal((await saved()).products[0].name,'TEST Soap');});
 await test('language switches core UI, product types and forms',async()=>{click('[data-lang=en]');await wait(()=>$('h1').textContent==='Products');click('#create');assert.equal($('#tab-packaging').textContent,'Packaging & logistics');click('#editor-close');});
 await test('backup restoration keeps data/photos and disconnects',async()=>{const s=await saved();await upload('backup',{format:'jason-backup',version:1,products:s.products,logistics:s.logistics,photos:{}});assert.equal((await saved()).connected,false);assert.deepEqual((await saved()).products,s.products);});
 assert.deepEqual(errors,[]);c.dom.window.close();
 const history=await setup();
 await test('checks suppress discontinued EAN replacements and expose active duplicates',async()=>{
  const rows=JSON.parse(fs.readFileSync(path.join(__dirname,'../../OrderSheet/products.json'),'utf8')).filter(p=>String(p.id)==='8596048005128');
  await history.upload('products',rows);history.click('[data-view=checks]');
  assert.ok(!history.$('#content').textContent.includes('Duplicitní EAN'));
  await history.upload('products',rows.map(p=>({...p,discontinued:false})));
  assert.equal(history.$$('tbody tr').filter(r=>r.textContent.includes('Duplicitní EAN / ID mezi aktivními produkty')).length,2);
  assert.deepEqual(history.errors,[]);
 });
 history.dom.window.close();
 // Deterministic API adapter checks using fake responses, no network.
 const d=await setup();let remote={products:[clone(fixture)],logistics:clone(logistics)},puts=[],fail=false,conflict=false;
 d.w.fetch=async(url,args={})=>{const n=new URL(url).pathname.split('/').pop();if(!String(url).startsWith('https://mock.test'))return {ok:false,status:404,text:async()=>''};if(args.method==='PUT'){const value=JSON.parse(args.body);puts.push({name:n,data:value});if(n==='products'&&fail)return {ok:false,status:500,text:async()=>'TEST FAILURE'};if(n!=='upload-image')remote[n]=value;return {ok:true,status:200};}return {ok:true,status:200,json:async()=>clone(conflict&&n==='products'?[{...fixture,name:'OTHER USER'}]:remote[n])};};
 await test('API connect reads without PUT; failed write retains local change',async()=>{d.click('#data-button');d.input('#field-api','https://mock.test');d.input('#field-images','https://images.test');d.click('#connect');d.click('#confirm-yes');await wait(()=>!d.$('#editor').open);assert.equal(puts.length,0);fail=true;d.click('[data-edit="0"]');d.input('#field-price','3.5');d.submit('#product-form');await wait(()=>!d.$('#retry').hidden);assert.equal(remote.products[0].price,1.2);assert.equal((await d.saved()).products[0].price,3.5);});
 await test('retry sends failed draft, using original API payload',async()=>{fail=false;d.click('#retry');await wait(()=>d.$('#save-status').textContent.includes('společných'));assert.equal(remote.products[0].price,3.5);assert.ok(puts.some(p=>p.name==='products'&&Array.isArray(p.data)));});
 await test('concurrent remote change prevents overwrite',async()=>{conflict=true;const before=puts.length;d.click('[data-edit="0"]');d.input('#field-price','4.5');d.submit('#product-form');await wait(()=>d.$('#toast').textContent.includes('jiný uživatel'));assert.equal(puts.length,before);assert.equal((await d.saved()).products[0].price,4.5);conflict=false;d.click('#retry');await wait(()=>d.$('#save-status').textContent.includes('společných'));});
 await test('partial two-file failure retains unsent products for retry',async()=>{fail=true;d.click('[data-view=keys]');d.click('[data-key-edit="Lilien"]');d.input('[name="CARTON:nr_of_items"]','8');d.submit('#key-form');await wait(()=>d.$('#confirm-dialog').open);d.click('#confirm-yes');await wait(()=>d.$('#toast').textContent.includes('TEST FAILURE'));assert.equal(remote.logistics.Lilien['500A'].CARTON.nr_of_items,8);assert.equal(remote.products[0].pack,12);assert.equal((await d.saved()).products[0].pack,8);fail=false;d.click('#retry');await wait(()=>remote.products[0].pack===8);});
 await test('photo pending queue uses original upload-image contract',async()=>{d.w.JasonStorage.jpeg=async()=> 'data:image/jpeg;base64,/9j/2Q==';d.click('[data-view=products]');d.click('[data-edit="0"]');d.click('#tab-photo');Object.defineProperty(d.$('#photo-input'),'files',{configurable:true,value:[{name:'arbitrary-name.png',type:'image/png'}]});d.$('#photo-input').dispatchEvent(new d.w.Event('change'));await wait(()=>d.$('#photo-preview').src.startsWith('data:'));d.submit('#product-form');await wait(()=>puts.some(p=>p.name==='upload-image'));const upload=puts.find(p=>p.name==='upload-image');assert.equal(upload.data.path,'OrderSheet/img/'+fixture.id+'.jpg');assert.equal(upload.data.content,'/9j/2Q==');await wait(async()=>(await d.saved()).pendingPhotos.length===0);});
 d.dom.window.close();
 const mixed={...clone(fixture),volume:{number:'4x50',unit:'g',note:'keep'},pack:99,discontinued:null,discontinued_date:null};
 let live={products:[mixed],logistics:clone(logistics)},livePuts=[];
 const f=await setup(true,async(url,args={})=>{const n=new URL(url).pathname.split('/').pop();if(args.method==='PUT'){livePuts.push(n);live[n]=JSON.parse(args.body);return {ok:true,status:200};}return {ok:true,status:200,json:async()=>clone(live[n])};});
 await test('hosted preview automatically reads the existing shared API without writes',async()=>{await wait(async()=>(await f.saved())?.connected);assert.equal((await f.saved()).products.length,1);assert.deepEqual(livePuts,[]);assert.match(f.$('#connection-label').textContent,/společným/);});
 await test('unchanged key save preserves historic packaging mismatch',async()=>{f.click('[data-view=keys]');f.click('[data-key-edit="Lilien"]');f.submit('#key-form');await wait(()=>!f.$('#editor').open);assert.equal((await f.saved()).products[0].pack,99);assert.deepEqual(livePuts,[]);});
 await test('multipack volume survives editing another field',async()=>{f.click('[data-view=products]');f.click('[data-edit="0"]');assert.equal(f.$('[name="volume-number"]').value,'4x50');f.input('#field-price','2.5');f.submit('#product-form');await wait(()=>live.products[0].price===2.5);assert.deepEqual(live.products[0].volume,mixed.volume);assert.equal(live.products[0].pack,99);assert.equal(live.products[0].discontinued,null);assert.equal(live.products[0].discontinued_date,null);await wait(async()=>!(await f.saved()).pendingPhotos.length&&f.$('#retry').hidden);});
 await test('manual refresh picks up legacy editor changes without writing',async()=>{live.products[0].name='LEGACY UPDATED';const before=livePuts.length;f.click('#refresh');await wait(async()=>(await f.saved()).products[0].name==='LEGACY UPDATED');assert.equal(livePuts.length,before);});
 await test('shared configuration is fixed and cannot create a second database',async()=>{f.click('#data-button');assert.equal(f.$('#field-api').readOnly,true);assert.equal(f.$('#field-api').value,'https://union-cosmetic.filipluchesi.workers.dev');assert.equal(f.$('#disconnect').hidden,true);f.click('#editor-close');});
 await test('backup restore in hosted preview retains common database and requires confirmation',async()=>{const s=await f.saved();await f.upload('backup',{format:'jason-backup',version:1,products:s.products,logistics:s.logistics,photos:{}});assert.equal((await f.saved()).connected,true);assert.equal((await f.saved()).api,'https://union-cosmetic.filipluchesi.workers.dev');});
 await test('automatic refresh never overwrites an open product form',async()=>{f.click('[data-edit="0"]');f.input('#field-name','DRAFT');live.products[0].name='ANOTHER EDIT';f.w.dispatchEvent(new f.w.Event('focus'));await sleep(30);assert.equal(f.$('#field-name').value,'DRAFT');assert.equal((await f.saved()).products[0].name,'LEGACY UPDATED');});
 f.dom.window.close();console.log(`ALL ${passed} DOM/API FLOW CHECKS PASSED`);
})().catch(e=>{console.error(e);process.exit(1);});

